[workspace]
resolver = "2"
members = ["benlang", "cfg", "compiler", "parser", "vm"]


[profile.release]
opt-level = 1
debug = true
strip = false

[profile.bench]
opt-level = 1
debug = true
strip = false
