[package]
name = "benlang"
version = "0.1.0"
edition = "2024"

[dependencies]
benlang-parser = {path = "../benlang-parser"}
benlang-cfg = {path = "../benlang-cfg"}
benlang-mem = {path = "../benlang-mem"}
petgraph = "0.7.1"